using System;                                                                                                                                                                                                                                                           
using System.Collections.Generic;                                                                                                                                                                                                                                       
using System.Drawing;                                                                                                                                                                                                                                                   
using System.Windows.Forms;                                                                                                                                                                                                                                             
using FacebookWrapper.ObjectModel;                                                                                                                                                                                                                                      
using FacebookWrapper;
using System.Threading;

namespace BasicFacebookFeatures                                                                                                                                                                                                                                         
{                                                                                                                                                                                                                                                                       
    public partial class FormMain : Form                                                                                                                                                                                                                                
    {                                                                                                                                                                                                                                                                   
        private FacebookWrapper.LoginResult m_LoginResult;                                                                                                                                                                                                              
        private readonly List<string> r_userPosts = new List<string>();                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                        
        public FormMain()                                                                                                                                                                                                                                               
        {                                                                                                                                                                                                                                                               
            InitializeComponent();                                                                                                                                                                                                                                      
            FacebookWrapper.FacebookService.s_CollectionLimit = 25;                                                                                                                                                                                                     
        }                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                        
        private void buttonLogin_Click(object sender, EventArgs e)                                                                                                                                                                                                      
        {                                                                                                                                                                                                                                                               
            try                                                                                                                                                                                                                                                         
            {                                                                                                                                                                                                                                                           
                Clipboard.SetText("design.patterns");                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                        
                if (m_LoginResult == null)                                                                                                                                                                                                                              
                {   
                    new Thread(login).Start();
                }                                                                                                                                                                                                                                                       
            }catch(Exception)                                                                                                                                                                                                                                           
            {                                                                                                                                                                                                                                                           
                MessageBox.Show("Failed to connect to Facebook.\nCheck your connection...");                                                                                                                                                                            
            }                                                                                                                                                                                                                                                           
        }                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                        
        private void login()                                                                                                                                                                                                                                            
        {                 
            buttonConnectAsDesig.Invoke(new Action(() => buttonConnectAsDesig.Enabled = false));
            buttonLogin.Invoke(new Action(() => buttonLogin.Enabled = false));
            m_LoginResult = FacebookService.Login(                                                                                                                                                                                                                      
                /// (This is Desig Patter's App ID. replace it with your own)                                                                                                                                                                                           
                textBoxAppID.Text,                                                                                                                                                                                                                                      
                /// requested permissions:                                                                                                                                                                                                                              
                "email",                                                                                                                                                                                                                                                
                "public_profile",                                                                                                                                                                                                                                       
                "user_friends",                                                                                                                                                                                                                                         
                "user_likes",                                                                                                                                                                                                                                           
                "user_photos",                                                                                                                                                                                                                                          
                "user_posts"                                                                                                                                                                                                                                            
                );                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                        
            if (string.IsNullOrEmpty(m_LoginResult.ErrorMessage))                                                                                                                                                                                                       
            {                                                                                                                                                                                                                                                           
                afterLogin();                                                                                                                                                                                                                                           
            }                                                                                                                                                                                                                                                           
        }                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                        
        private void buttonConnectAsDesig_Click(object sender, EventArgs e)                                                                                                                                                                                             
        {                                                                                                                                                                                                                                                               
            try                                                                                                                                                                                                                                                         
            {                                                                                                                                                                                                                                                           
                m_LoginResult = FacebookService.Connect("EAAUm6cZC4eUEBPZCFs9rJRpwlUmdHcPvU1tUNkIyP37zRZCjSvfdHaW5t3xsOnUL0bEKHL8Snjk6AZC3O32KWEbaItglEnXWQ2zEMXHqsdfdv0ecXNs3hO69juHrZCfRN9FGvfuJZAXhP4Pm57DRRoDeB8De6ZABnfrRflh6zgPwnavpyHS3ZCYX1E6K1QLTHff5sAZDZD"); 
                afterLogin();                                                                                                                                                                                                                                          
            }                                                                                                                                                                                                                                                          
            catch (Exception)                                                                                                                                                                                                                                          
            {                                                                                                                                                                                                                                                          
                MessageBox.Show(m_LoginResult.ErrorMessage, "Login Failed");                                                                                                                                                                                           
            }                                                                                                                                                                                                                                                          
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void afterLogin()                                                                                                                                                                                                                                      
        {           
            buttonLogin.Invoke(new Action(() => 
                buttonLogin.Text = $"Logged in as {m_LoginResult.LoggedInUser.Name}"));
            buttonLogin.Invoke(new Action(() =>
                buttonLogin.BackColor = Color.LightGreen));
            buttonLogin.Invoke(new Action(() =>
                buttonLogin.Enabled = false));
            buttonLogout.Invoke(new Action(() =>
                buttonLogout.Enabled = true));
            new Thread(setUpUserInformationDisplay).Start();
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void setUpUserInformationDisplay()                                                                                                                                                                                                                     
        {                                                                                                                                                                                                                                                              
            if (m_LoginResult == null)                                                                                                                                                                                                                                 
            {                                                                                                                                                                                                                                                          
                throw new Exception("User is not logged in");                                                                                                                                                                                                          
            }

            User user = m_LoginResult.LoggedInUser;

            buttonConnectAsDesig.Invoke(new Action(() => buttonConnectAsDesig.Enabled = false));
            pictureBoxProfile.Invoke(new Action(()=> 
                pictureBoxProfile.ImageLocation = user.PictureNormalURL));
            new Thread(() => attachBindingSourceAfterLogin<User>(userBindingSource, new FacebookObjectCollection<User> { user })).Start();
            new Thread(() => attachBindingSourceAfterLogin<Post>(postsBindingSource, user.Posts)).Start();
            new Thread(() => attachBindingSourceAfterLogin<Page>(groupBindingSource, user.LikedPages)).Start();
            new Thread(() => attachBindingSourceAfterLogin<Page>(musicBindingSource, user.Music)).Start();
            new Thread(() => attachBindingSourceAfterLogin<User>(friendsBindingSource, user.Friends)).Start();

            profilePictureBox.Invoke(new Action(() => profilePictureBox.ImageLocation = user.PictureNormalURL));
            higherOrLowerBtn.Invoke(new Action(() => higherOrLowerBtn.Enabled = true));
            buttonMostPhotogenicYear.Invoke(new Action(() => buttonMostPhotogenicYear.Enabled = true));                                                                                                                                                                                                                   
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void attachBindingSourceAfterLogin<T>(BindingSource i_BindingSource, FacebookObjectCollection<T> i_ItemsToDisplay) where T : FacebookObject                                                                                                                              
        {
            this.Invoke(new Action(() => i_BindingSource.DataSource = i_ItemsToDisplay));
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void buttonLogout_Click(object sender, EventArgs e)                                                                                                                                                                                                    
        {                                                                                                                                                                                                                                                              
            FacebookService.LogoutWithUI();                                                                                                                                                                                                                            
            buttonLogin.Text = "Login";                                                                                                                                                                                                                                
            buttonLogin.BackColor = buttonLogout.BackColor;                                                                                                                                                                                                            
            m_LoginResult = null;                                                                                                                                                                                                                                      
            buttonLogin.Enabled = true;                                                                                                                                                                                                                                
            buttonLogout.Enabled = false;                                                                                                                                                                                                                              
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        private void likedFriendsListBox_SelectedIndexChanged(object sender, EventArgs e)                                                                                                                                                                              
        {                                                                                                                                                                                                                                                              
            friendsPictureBox.ImageLocation = (likedFriendsListBox.SelectedItem as Page).PictureNormalURL;                                                                                                                                                             
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void higherOrLowerBtn_Click(object sender, EventArgs e)                                                                                                                                                                                                
        {                                                                                                                                                                                                                                                              
            if (m_LoginResult == null || m_LoginResult.LoggedInUser == null)                                                                                                                                                                                           
            {                                                                                                                                                                                                                                                          
                MessageBox.Show("Please login first.");                                                                                                                                                                                                                
                return;                                                                                                                                                                                                                                                
            }                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                       
            HigherOrLowerForm higherOrLowerForm = new HigherOrLowerForm(m_LoginResult.LoggedInUser);
            new Thread(() => new HigherOrLowerForm(m_LoginResult.LoggedInUser).ShowDialog()).Start();                                                                                                                                                                                                                                                           
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void buttonMostPhotogenicYear_Click(object sender, EventArgs e)                                                                                                                                                                                        
        {                                                                                                                                                                                                                                                              
            if (m_LoginResult == null || m_LoginResult.LoggedInUser == null)                                                                                                                                                                                           
            {                                                                                                                                                                                                                                                          
                MessageBox.Show("Please login first.");                                                                                                                                                                                                                
                return;                                                                                                                                                                                                                                                
            }                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                       
            MostPhotogenicYearAnalyzerForm mostPhotogenicYearAnalyzerForm = new MostPhotogenicYearAnalyzerForm(m_LoginResult.LoggedInUser);                                                                                                                            
                                                                                                                                                                                                                                                                       
            {                                                                                                                                                                                                                                                          
                mostPhotogenicYearAnalyzerForm.ShowDialog();                                                                                                                                                                                                           
            }                                                                                                                                                                                                                                                          
        }

        private void selectPostBtn_Click(object sender, EventArgs e)
        {
            Post selectedPost = postsComboBox.SelectedItem as Post;

            if (selectedPost == null)
            {
                currentFavoritePostLabel.Text = "No post selected.";
                return;
            }

            string textToShow = selectedPost.Message;

            if (string.IsNullOrEmpty(textToShow))
            {
                textToShow = "[Post has no message]";
            }

            currentFavoritePostLabel.Text = textToShow;
        }

        private void postsComboBox_SelectedIndexChanged(object sender, EventArgs e)                                                                                                                                                                                    
        {                                                                                                                                                                                                                                                              
            selectPostBtn.Enabled = true;                                                                                                                                                                                                                              
        }                                                                                                                                                                                                                                                              
    }                                                                                                                                                                                                                                                                  
}                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                       