using System;                                                                                                                                                                                                                                                           
using System.Collections.Generic;                                                                                                                                                                                                                                       
using System.Drawing;                                                                                                                                                                                                                                                   
using System.Windows.Forms;                                                                                                                                                                                                                                             
using FacebookWrapper.ObjectModel;                                                                                                                                                                                                                                      
using FacebookWrapper;
using System.Threading;

namespace BasicFacebookFeatures                                                                                                                                                                                                                                         
{                                                                                                                                                                                                                                                                       
    public partial class FormMain : Form                                                                                                                                                                                                                                
    {                                                                                                                                                                                                                                                                   
        private FacebookWrapper.LoginResult m_LoginResult;                                                                                                                                                                                                              
        private readonly List<string> r_userPosts = new List<string>();                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                        
        public FormMain()                                                                                                                                                                                                                                               
        {                                                                                                                                                                                                                                                               
            InitializeComponent();                                                                                                                                                                                                                                      
            FacebookWrapper.FacebookService.s_CollectionLimit = 25;                                                                                                                                                                                                     
        }                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                        
        private void buttonLogin_Click(object sender, EventArgs e)                                                                                                                                                                                                      
        {                                                                                                                                                                                                                                                               
            try                                                                                                                                                                                                                                                         
            {                                                                                                                                                                                                                                                           
                Clipboard.SetText("design.patterns");                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                        
                if (m_LoginResult == null)                                                                                                                                                                                                                              
                {   
                    new Thread(login).Start();
                }                                                                                                                                                                                                                                                       
            }catch(Exception)                                                                                                                                                                                                                                           
            {                                                                                                                                                                                                                                                           
                MessageBox.Show("Failed to connect to Facebook.\nCheck your connection...");                                                                                                                                                                            
            }                                                                                                                                                                                                                                                           
        }                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                        
        private void login()                                                                                                                                                                                                                                            
        {                 
            buttonConnectAsDesig.Invoke(new Action(() => buttonConnectAsDesig.Enabled = false));
            buttonLogin.Invoke(new Action(() => buttonLogin.Enabled = false));
            m_LoginResult = FacebookService.Login(                                                                                                                                                                                                                      
                /// (This is Desig Patter's App ID. replace it with your own)                                                                                                                                                                                           
                textBoxAppID.Text,                                                                                                                                                                                                                                      
                /// requested permissions:                                                                                                                                                                                                                              
                "email",                                                                                                                                                                                                                                                
                "public_profile",                                                                                                                                                                                                                                       
                "user_friends",                                                                                                                                                                                                                                         
                "user_likes",                                                                                                                                                                                                                                           
                "user_photos",                                                                                                                                                                                                                                          
                "user_posts"                                                                                                                                                                                                                                            
                );                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                        
            if (string.IsNullOrEmpty(m_LoginResult.ErrorMessage))                                                                                                                                                                                                       
            {                                                                                                                                                                                                                                                           
                afterLogin();                                                                                                                                                                                                                                           
            }                                                                                                                                                                                                                                                           
        }                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                        
        private void buttonConnectAsDesig_Click(object sender, EventArgs e)                                                                                                                                                                                             
        {                                                                                                                                                                                                                                                               
            try                                                                                                                                                                                                                                                         
            {                                                                                                                                                                                                                                                           
                m_LoginResult = FacebookService.Connect("EAAUm6cZC4eUEBPZCFs9rJRpwlUmdHcPvU1tUNkIyP37zRZCjSvfdHaW5t3xsOnUL0bEKHL8Snjk6AZC3O32KWEbaItglEnXWQ2zEMXHqsdfdv0ecXNs3hO69juHrZCfRN9FGvfuJZAXhP4Pm57DRRoDeB8De6ZABnfrRflh6zgPwnavpyHS3ZCYX1E6K1QLTHff5sAZDZD"); 
                afterLogin();                                                                                                                                                                                                                                          
            }                                                                                                                                                                                                                                                          
            catch (Exception)                                                                                                                                                                                                                                          
            {                                                                                                                                                                                                                                                          
                MessageBox.Show(m_LoginResult.ErrorMessage, "Login Failed");                                                                                                                                                                                           
            }                                                                                                                                                                                                                                                          
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void afterLogin()                                                                                                                                                                                                                                      
        {                                                                                                                                                                                                                                                              
            buttonLogin.Text = $"Logged in as {m_LoginResult.LoggedInUser.Name}";                                                                                                                                                                                      
            buttonLogin.BackColor = Color.LightGreen;   
            buttonLogin.Enabled = false;                                                                                                                                                                                                                               
            buttonLogout.Enabled = true;  
            new Thread(setUpUserInformationDisplay).Start();
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void setUpUserInformationDisplay()                                                                                                                                                                                                                     
        {                                                                                                                                                                                                                                                              
            if (m_LoginResult == null)                                                                                                                                                                                                                                 
            {                                                                                                                                                                                                                                                          
                throw new Exception("User is not logged in");                                                                                                                                                                                                          
            }

            buttonConnectAsDesig.Invoke(new Action(() => buttonConnectAsDesig.Enabled = false));
            pictureBoxProfile.Invoke(new Action(()=> 
                pictureBoxProfile.ImageLocation = m_LoginResult.LoggedInUser.PictureNormalURL));
            User user = m_LoginResult.LoggedInUser;                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                       
            r_userPosts.Clear();                                                                                                                                                                                                                                       
            foreach (Post post in user.Posts)                                                                                                                                                                                                                          
            {                                                                                                                                                                                                                                                          
                string postStatus = post.Message;                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                       
                if (!string.IsNullOrEmpty(postStatus))                                                                                                                                                                                                                 
                {                                                                                                                                                                                                                                                      
                    r_userPosts.Add(post.Message);                                                                                                                                                                                                                     
                }                                                                                                                                                                                                                                                      
            }                                                                                                                                                                                                                                                          
            
            new Thread(() => updateListBoxAfterLogin<Page>(likedGroupsListBox, user.LikedPages)).Start();
            new Thread(() => updateListBoxAfterLogin<Page>(likedMusicListBox, user.Music)).Start();
            new Thread(() => updateListBoxAfterLogin<User>(likedFriendsListBox, user.Friends)).Start();
            profilePictureBox.Invoke(new Action(() => profilePictureBox.ImageLocation = user.PictureNormalURL));
            postsComboBox.Invoke(new Action(() => postsComboBox.DataSource = r_userPosts));
            higherOrLowerBtn.Invoke(new Action(() => higherOrLowerBtn.Enabled = true));
            buttonMostPhotogenicYear.Invoke(new Action(() => buttonMostPhotogenicYear.Enabled = true));                                                                                                                                                                                                                   
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void updateListBoxAfterLogin<T>(ListBox i_ListBox, FacebookObjectCollection<T> i_ItemsToDisplay) where T : FacebookObject                                                                                                                              
        {
            i_ListBox.Invoke(new Action(() =>i_ListBox.Items.Clear()));                                                                                                                                                                                                                                   
            i_ListBox.Invoke(new Action(() => i_ListBox.DataSource = i_ItemsToDisplay));                                                                                                                                                                                                                   
            i_ListBox.Invoke(new Action(() => i_ListBox.DisplayMember = "Name"));                                                                                                                                                                                                                          
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void buttonLogout_Click(object sender, EventArgs e)                                                                                                                                                                                                    
        {                                                                                                                                                                                                                                                              
            FacebookService.LogoutWithUI();                                                                                                                                                                                                                            
            buttonLogin.Text = "Login";                                                                                                                                                                                                                                
            buttonLogin.BackColor = buttonLogout.BackColor;                                                                                                                                                                                                            
            m_LoginResult = null;                                                                                                                                                                                                                                      
            buttonLogin.Enabled = true;                                                                                                                                                                                                                                
            buttonLogout.Enabled = false;                                                                                                                                                                                                                              
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void likedMusicListBox_SelectedIndexChanged(object sender, EventArgs e)                                                                                                                                                                                
        {                                                                                                                                                                                                                                                              
            MusicPictureBox.ImageLocation = (likedMusicListBox.SelectedItem as Page).PictureNormalURL;                                                                                                                                                                 
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void likedGroupsListBox_SelectedIndexChanged(object sender, EventArgs e)                                                                                                                                                                               
        {                                                                                                                                                                                                                                                              
            GroupsPictureBox.ImageLocation = (likedGroupsListBox.SelectedItem as Page).PictureNormalURL;                                                                                                                                                               
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void likedFriendsListBox_SelectedIndexChanged(object sender, EventArgs e)                                                                                                                                                                              
        {                                                                                                                                                                                                                                                              
            friendsPictureBox.ImageLocation = (likedFriendsListBox.SelectedItem as Page).PictureNormalURL;                                                                                                                                                             
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void higherOrLowerBtn_Click(object sender, EventArgs e)                                                                                                                                                                                                
        {                                                                                                                                                                                                                                                              
            if (m_LoginResult == null || m_LoginResult.LoggedInUser == null)                                                                                                                                                                                           
            {                                                                                                                                                                                                                                                          
                MessageBox.Show("Please login first.");                                                                                                                                                                                                                
                return;                                                                                                                                                                                                                                                
            }                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                       
            HigherOrLowerForm higherOrLowerForm = new HigherOrLowerForm(m_LoginResult.LoggedInUser);                                                                                                                                                                   
                                                                                                                                                                                                                                                                       
            higherOrLowerForm.ShowDialog();                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void buttonMostPhotogenicYear_Click(object sender, EventArgs e)                                                                                                                                                                                        
        {                                                                                                                                                                                                                                                              
            if (m_LoginResult == null || m_LoginResult.LoggedInUser == null)                                                                                                                                                                                           
            {                                                                                                                                                                                                                                                          
                MessageBox.Show("Please login first.");                                                                                                                                                                                                                
                return;                                                                                                                                                                                                                                                
            }                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                       
            MostPhotogenicYearAnalyzerForm mostPhotogenicYearAnalyzerForm = new MostPhotogenicYearAnalyzerForm(m_LoginResult.LoggedInUser);                                                                                                                            
                                                                                                                                                                                                                                                                       
            {                                                                                                                                                                                                                                                          
                mostPhotogenicYearAnalyzerForm.ShowDialog();                                                                                                                                                                                                           
            }                                                                                                                                                                                                                                                          
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void selectPostBtn_Click(object sender, EventArgs e)                                                                                                                                                                                                   
        {                                                                                                                                                                                                                                                              
            string chosenPost = postsComboBox.Items[postsComboBox.SelectedIndex] as string;                                                                                                                                                                            
                                                                                                                                                                                                                                                                       
            currentFavoritePostLabel.Text = chosenPost;                                                                                                                                                                                                                
        }                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                       
        private void postsComboBox_SelectedIndexChanged(object sender, EventArgs e)                                                                                                                                                                                    
        {                                                                                                                                                                                                                                                              
            selectPostBtn.Enabled = true;                                                                                                                                                                                                                              
        }                                                                                                                                                                                                                                                              
    }                                                                                                                                                                                                                                                                  
}                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                       